### ISSUE TITLE
Bug: decimal amounts are subject to rounding errors

### ISSUE THREAD

**Issue by shahyar** [scastiel/spliit2#1]
Hey there. Cool project. As a test, I created a new expense and gave it the value `19.15`. The UI then showed this as having a value of `19.14`. This is a [very common problem in JavaScript](https://stackoverflow.com/questions/11832914/how-to-round-to-at-most-2-decimal-places-if-necessary).

**Comment by scastiel** [comment]
Thanks @shahyar for letting me know! Actually a silly rounding mistake (calling `Math.floor` instead of `Math.round`). JavaScript can be annoying when dealing with decimal numbers, which is why I store only integers and convert to a decimal just for display.
