### ISSUE TITLE
Store and display date of transaction

### ISSUE THREAD

**Issue by LIRIKKER** [scastiel/spliit2#17]
Would be great to have the ability to add the date of the transaction onto the Expense.
With this the homepage of the group should then be sorted by date.
This should also be broken down by months but still remain on the same page.
i.e

January 2024
3rd - Transition 1- £50
2nd - Transition 2 - $23
1st - Transition 3 - £45

Break

December 2023
31st - Transition - 4 £44
21st - Transition - 5 £123
4th - Transition - 6 £12

Break

November 2023

**Comment by scastiel** [comment]
Date is now stored and displayed (#24), I created a separate issue (#27) to group expenses by date.
