### ISSUE TITLE
Group expenses by date

### ISSUE THREAD

**Issue by scastiel** [scastiel/spliit2#27]
In the expense list, now that we store the expense date (#17), we can group them by date.

**Comment by ChristopherJohnston** [comment]
It might also be good to hide expenses before the latest reimbursement by default.

I have tested a group with ~2800 items and the page becomes a little slow when rendering so many rows!

**Comment by scastiel** [comment]
A reimbursement doesn’t necessarily related to all expenses, so I can’t see how to know which transactions to hide. But you’re right, the page becomes slow when displaying many expenses.

A good alternative could be to implement some kind of pagination. Just created issue #30 for this feature.
