### ISSUE TITLE
Expense "Paid by X on" dates showing incorrect

### ISSUE THREAD

**Issue by ssladmin22** [scastiel/spliit2#33]
Dates appear 1 day previous on the 'dashboard' view. Clicking to open an individual expense will show the correct date:

![image](https://github.com/scastiel/spliit2/assets/92600859/42992711-a9d7-4d5c-b5b7-04cc534fe8b4)

^Incorrect

![image](https://github.com/scastiel/spliit2/assets/92600859/3827032a-7f19-4f93-9e81-9b7a2c2b36bd)

^Correct

**Comment by scastiel** [comment]
Thanks @sslovelady for creating the issue. It should be fixed now :)
