### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by dmlls** [scastiel/spliit2#40]
Hi! I'm loving the app so far and already managed to get a couple of friends on board.

I would like to contribute to the project not only with issues and feature requests, but also monetarily, in order to cover the hosting expenses and ensure the continuity of the project!

I haven't found any way of doing so, is there any? Otherwise I think adding a link on https://spliit.app/ or here on GitHub would be a good idea :)

**Comment by scastiel** [comment]
Hi @dmlls, that is so kind, thanks :)

I’ll set up something like a buymeacoffee or ko-fi account soon.

**Comment by korg91** [comment]
I've just found out about the [enshittification](https://en.wikipedia.org/wiki/Enshittification) of Splitwise and, thanks to that, about this app. I'd also be happy to donate :)

**Comment by scastiel** [comment]
I just added a _Support us_ button in the application footer (as well as in the [README](https://github.com/scastiel/spliit2/blob/main/README.md#contribute)). 😊

**Comment by dmlls** [comment]
@scastiel Awesome, it works! ;)

Just a quick heads-up, the font color in dark mode seems to be off:

<img width="500" alt="support-us" src="https://github.com/scastiel/spliit2/assets/22967053/316bcbd4-265c-4b6b-bc02-f0b3fc23dc87">
