### ISSUE TITLE
Export group expenses as JSON

### ISSUE THREAD

**Issue by jingchengx** [scastiel/spliit2#42]
One thing I liked about splitwise is the ability to download a json file of all the expenses.  It'd be nice to have this feature here.

**Comment by scastiel** [comment]
There is now an Export button above the expense list, that triggers a download of expenses as JSON:

![Screenshot 2024-01-15 at 11 46 03](https://github.com/scastiel/spliit2/assets/301948/fa65f7c5-ccc0-4099-854b-ccdde7121bf9)

In the future, it would be interesting to offer a CSV export, maybe following the format used by Splitwise (see #22).
