### ISSUE TITLE
Application error when filling out date field from keyboard

### ISSUE THREAD

**Issue by korg91** [scastiel/spliit2#43]
When filling the date using the keyboard, if more than 4 digits are inserted in the year field (obviously by mistake ;) ), the app crashes and shows the following error:

`Application error: a client-side exception has occurred (see the browser console for more information).`

The same happens if I type `0` as the first digit in any of the date fields.

This is from Firefox 121.0 (Ubuntu)

Thanks for the excellent app!

**Comment by scastiel** [comment]
Thanks @korg91 for submitting the issue. It should be fixed now 😉

**Comment by korg91** [comment]
Well, that was quick! Thank you (and made a small donation) :)
