### ISSUE TITLE
Ability to archive groups when they’re settled up

### ISSUE THREAD

**Issue by acuteengle** [scastiel/spliit2#44]
Hello!

I've really enjoyed using spliit for the past few months. I originally found it because I was searching for an alternative to Splitwise once they started to only allow you to enter 3 expenses a day on a free-plan. I was even happier when I realized that this project was open source and I could help contribute! That being said, would love to help out!

My feature request is to some how make it easier to see which of the spliit groups are "settled up". On the "groups" page, all the groups keep changing order based on which one I viewed most recently and it's hard to remember which ones are "settled up" and which ones are still "awaiting reimbursements" or I am still adding expenses to.

I had a few different ideas:

1. Separate sections on the "groups" page (i.e. "Starred", "Recent", "Settled up")
2. Have an icon/indicator on the "group" card that just says "Settled up"

I also saw issue (https://github.com/scastiel/spliit2/issues/9) and while I think that it's nice that this could help clean up the db and save space, it's also nice to have a historical record of all past groups and those expenses so you can refer back to see which expenses were included in each group.

**Comment by scastiel** [comment]
Hi @acuteengle, I like the idea of indicating which groups are settled up, but I’m afraid it adds too much load on the database. In your implementation PR (thank you for that!), you fetch all expenses for all the groups displayed in the recent groups, which can be very expensive. I can’t think of any other way to implement this behaviour though.

I wonder if it wouldn’t be a better idea to offer to manually “mark as settled up” or “archive” groups from the recent groups page. The information would be stored in the local storage, and the archived groups would be hidden by default (therefore preventing some load on the database), but could still be accessed and “un-archived”.

What do you think?

**Comment by acuteengle** [comment]
> I like the idea of indicating which groups are settled up, but I’m afraid it adds too much load on the database. In your implementation PR (thank you for that!), you fetch all expenses for all the groups displayed in the recent groups, which can be very expensive. I can’t think of any other way to implement this behaviour though.

Makes sense^ I was also thinking it was unfortunate that we have to call `getGroupExpenses` for each group to get the info needed.

> I wonder if it wouldn’t be a better idea to offer to manually “mark as settled up” or “archive” groups from the recent groups page. The information would be stored in the local storage, and the archived groups would be hidden by default (therefore preventing some load on the database), but could still be accessed and “un-archived”.

I do like this idea^ I'll update my PR to implement something like this. Instead of hiding the groups, I'll put an "Archived" header and have the archived groups beneath it so users can still access the historical information easily if they wish.

**Comment by acuteengle** [comment]
@scastiel https://github.com/scastiel/spliit2/pull/45 is ready for another look!
