### ISSUE TITLE
Development of iOS and Android Apps

### ISSUE THREAD

**Issue by COValhalla** [scastiel/spliit2#8]
I found this project after searching for alternatives to Splitwise. They've recently implemented a limitation that allows only four (4) expense submissions per day before requiring a paid upgrade, which I find unacceptable.

I'd be open to contributing to this project. My idea is to utilize React Native to maintain a single codebase for building apps for both iOS and Android platforms. We could use Native Wind to ensure consistent styling across both platforms.

**Comment by scastiel** [comment]
Hi @COValhalla, one of the ideas behind Spliit is to keep only a webapp, to minimize the steps required to use it. No need to create an account, to enter an email, or to install an app.

I’m trying to make it a Progressive Web App so it looks as much as possible to an app though, but it isn’t part of the plan to create native versions of it.

But feel free to take inspiration from it if you want, it is open source :)
